language: node_js
cache:
    directories:
        - ~/.npm
notifications:
    email: false
node_js:
    - '10'
    - '9'
    - '8'
jobs:
    include:
        - 
            stage: build
            script: yarn build
            node_js: lts/*
        -
            stage: release
            node_js: lts/*
            deploy:
                provider: script
                skip_cleanup: true
                script: yarn semantic-release
branches:
    except:
        - /^v\d+\.\d+\.\d+$/
