language: node_js
cache:
    directories:
        - ~/.npm
notifications:
    email: false
node_js: lts/*
before_install:
    - yarn global add greenkeeper-lockfile@1
jobs:
    include:
        -
            stage: test
            script:
                - yarn test --coverage
            before_script: greenkeeper-lockfile-update
            after_script: greenkeeper-lockfile-upload
        -
            stage: deploy
            if: branch = master
            script:
                - yarn build
                - yarn test dist
            after_success: travis-deploy-once "yarn semantic-release"